### ISSUE TITLE
'millis' was not declared in this scope

### ISSUE THREAD

**Issue by GregSawin** [pkourany/elapsedMillis#2]
Verifying code using this library in Particle Build v0.4.5 on a Photon sometimes fails with this error:
```
elapsedMillis/elapsedMillis.h:34:36: error: 'millis' was not declared in this scope
  elapsedMillis(void) { ms = millis()

**Comment by GregSawin** [comment]
Nevermind, it's a build bug when an #include is the first line; unrelated to your code.

**Comment by joscha** [comment]
@GregSawin can you elaboate? I am seeing the same error, but I am not sure how to fix it.

**Comment by GregSawin** [comment]
Add a blank line or a comment above it so the first line of your program does not start with #include
